[tool.poetry]

name = "Gradem"
version = "0.0.1"
description = "MYP Design grading made intuitive"

authors = [
    "Cobbi Liu"
]

[tool.poetry.dependencies]

python = ">=3.9"
pandas = ">=1.2.4"
numpy = ">=1.20.1"
matplotlib = ">=3.3.4"
